// <auto-generated />
namespace YoutubeNote.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_columns));
        
        string IMigrationMetadata.Id
        {
            get { return "201706151118287_added_columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
