// <auto-generated />
namespace YoutubeNote.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class created_annotation_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(created_annotation_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201707241941468_created_annotation_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
